server:
  port: 9001

eureka:
  instance:
    hostname: localhost
  client:
    # 以下两项一定要是false，表明自己是服务器，而不需要从其他主机发现服务
    
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
spring:
  application:
    name: note-eureka