server:
  port: 8080
  tomcat:
    max-http-header-size: 8192


spring:
  application:
    name: jia-code
  profiles:
    active: dev
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.alibaba.druid.pool.DruidData
    #url: mysql://192.168.3.175:3306/gonghuitest?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    url: jdbc:mysql://192.168.3.175:3306/gonghuitest?useUnicode=true&characterEncoding=utf8
    username: gonghuitest
    password: gongHUI!@34
    tomcat:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    enabled: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

    
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.jia.code.generator.entity
  
  
  
   

 #jdbc:mysql://192.168.3.175:3306/gonghuitest?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#gonghuitest
#gongHUI!@34