server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka/

spring:
  application:
    name: note-service
  profiles:
    active: dev
  datasource:
   # driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.alibaba.druid.pool.DruidData
    druid:
      url: mysql://192.168.3.175:3306/gonghuitest?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: gonghuitest
      password: gongHUI!@34
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000
    
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.weixin.entity

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
  
   

 #jdbc:mysql://192.168.3.175:3306/gonghuitest?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#gonghuitest
#gongHUI!@34