server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka/

spring:
  application:
    name: note-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: mysql://192.168.31.107:3306/wexin?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: wexin
    password: wexin
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
   

 #jdbc:mysql://192.168.3.175:3306/gonghuitest?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#gonghuitest
#gongHUI!@34